.TH QUOTE 1 "March 2025" "1.0" "User Commands"
.SH NAME
quote \- Retrieve a random quote from an online API.

.SH SYNOPSIS
.B quote

.SH DESCRIPTION
The \fBquote\fR command fetches a random quote from the Quotable API (\fIhttp://api.quotable.io/random\fR) and displays it in the terminal.

.SH OPTIONS
This command does not accept any options.

.SH EXAMPLES
To get a random quote, simply run:
.PP
.nf
quote
.fi

.SH EXIT STATUS
Returns 0 on success, non-zero on failure.

.SH NOTES
- Requires an active internet connection.
- If the API is unreachable, an error message is displayed.

.SH AUTHOR
Mohammad Abu Mattar
.br
GitHub: https://github.com/MKAbuMattar/.dotfiles
